server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: server
          __path__: /var/log/app/*/*.log
    pipeline_stages:
      - regex:
          expression: "^(?P<filename>.*)/(?P<date>\\d{4}-\\d{2}-\\d{2})/(?P<logtype>.*)\\.log$"
      - labels:
          date:
          logtype:
    relabel_configs:
      - source_labels: ['__path__']
        target_label: filename
      - source_labels: ['logtype']
        target_label: log_type
      - source_labels: ['date']
        target_label: log_date